name: Build and Publish to Pages
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: Raiden0456/VuePagesAction@1.0.2
      with:
        username: 'Raiden0456'
        reponame: 'bento-startup'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
